#!/usr/bin/env python3
"""Build the RackUp billiard hall directory pages from data/venues.json.

Run from anywhere, Python 3.8+ and the standard library only:
  python tools/build_directory.py                 rebuild every directory page
  python tools/build_directory.py --import PATH   refresh data/venues.json from the app repo's
                                                  data/venues-backup.json, then rebuild
  python tools/build_directory.py --check         exit 1 if the committed pages are stale
"""
import argparse
import html
import json
import re
import shutil
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "venues.json"
BASE_URL = "https://getrackup.com"
APP_STORE = "https://apps.apple.com/gr/app/rackup-find-an-opponent/id6800614202"
PLAY_STORE = "https://play.google.com/store/apps/details?id=com.rackup.app"
APP_STORE_ID = "6800614202"
# The pt from App Store Connect, the same value as PROVIDER_TOKEN in go/go.js. While it is
# empty the App Store links stay plain; once set, every page's link carries ct=web-<campaign>.
PROVIDER_TOKEN = "129299799"
# A page's campaign: lowercase letters, digits and single hyphens. "web-" plus 26 is Apple's 30.
CAMPAIGN = re.compile(r"[a-z0-9]+(-[a-z0-9]+)*")
CAMPAIGN_MAX = 26
# Hand-written pages whose store links the build tags too: file -> site path.
HAND_PAGES = {"index.html": "", "en/index.html": "en/", "support.html": "support.html", "404.html": "404.html"}
# The two homes: each carries the counts and the city grid, in its own language.
HOMES = {"index.html": "el", "en/index.html": "en"}
GRID_START, GRID_END = "<!-- city-grid -->", "<!-- /city-grid -->"
EMAIL = "rackupbilliard@gmail.com"
EL_ROOT = "mpiliardo"
EN_ROOT = "en/billiards"
MARKER = "<!-- Generated by tools/build_directory.py from data/venues.json. Do not edit by hand. -->"

# The only fields copied out of venues-backup.json. This repo is public, so
# coordinates, prices, hours and amenities never enter it.
PUBLIC_FIELDS = ("id", "name", "city", "address", "sortOrder", "phone", "website")

# English key as stored on venue docs -> (slug, Greek name, Greek "in the city").
# Mirrors GreekCity.kt in the app. A new directory city must be added here.
CITIES = {
    "Athens": ("athens", "Αθήνα", "στην Αθήνα"),
    "Thessaloniki": ("thessaloniki", "Θεσσαλονίκη", "στη Θεσσαλονίκη"),
    "Heraklion": ("heraklion", "Ηράκλειο", "στο Ηράκλειο"),
    "Larissa": ("larissa", "Λάρισα", "στη Λάρισα"),
    "Chania": ("chania", "Χανιά", "στα Χανιά"),
    "Rethymno": ("rethymno", "Ρέθυμνο", "στο Ρέθυμνο"),
    "Chalkida": ("chalkida", "Χαλκίδα", "στη Χαλκίδα"),
    "Kavala": ("kavala", "Καβάλα", "στην Καβάλα"),
    "Patras": ("patras", "Πάτρα", "στην Πάτρα"),
    "Volos": ("volos", "Βόλος", "στον Βόλο"),
    "Ioannina": ("ioannina", "Ιωάννινα", "στα Ιωάννινα"),
    "Rhodes": ("rhodes", "Ρόδος", "στη Ρόδο"),
    "Kalamata": ("kalamata", "Καλαμάτα", "στην Καλαμάτα"),
    "Korinthos": ("korinthos", "Κόρινθος", "στην Κόρινθο"),
    "Sparti": ("sparti", "Σπάρτη", "στη Σπάρτη"),
    "Salamina": ("salamina", "Σαλαμίνα", "στη Σαλαμίνα"),
    "Serres": ("serres", "Σέρρες", "στις Σέρρες"),
    "Kozani": ("kozani", "Κοζάνη", "στην Κοζάνη"),
    "Lamia": ("lamia", "Λαμία", "στη Λαμία"),
    "Corfu": ("corfu", "Κέρκυρα", "στην Κέρκυρα"),
    "Preveza": ("preveza", "Πρέβεζα", "στην Πρέβεζα"),
    "Argos": ("argos", "Άργος", "στο Άργος"),
    "Nafplio": ("nafplio", "Ναύπλιο", "στο Ναύπλιο"),
    "Agios Nikolaos": ("agios-nikolaos", "Άγιος Νικόλαος", "στον Άγιο Νικόλαο"),
    "Chios": ("chios", "Χίος", "στη Χίο"),
    "Aigio": ("aigio", "Αίγιο", "στο Αίγιο"),
    "Naxos": ("naxos", "Νάξος", "στη Νάξο"),
}

# Figure dash, en dash, em dash, horizontal bar. None may reach a page.
DASHES = re.compile("[" + "".join(map(chr, (0x2012, 0x2013, 0x2014, 0x2015))) + "]")
DESCRIPTION_LIMIT = 170


def esc(text):
    """Safe in text and in double-quoted attributes; apostrophes stay readable."""
    return html.escape(str(text), quote=False).replace('"', "&quot;")


def fold(text):
    """Accent-free lowercase key, so Greek names sort alphabetically."""
    decomposed = unicodedata.normalize("NFD", text)
    return "".join(c for c in decomposed if not unicodedata.combining(c)).lower()


def plural_el(n):
    return f"{n} αίθουσα" if n == 1 else f"{n} αίθουσες"


def plural_en(n):
    return f"{n} hall" if n == 1 else f"{n} halls"


# ---------------------------------------------------------------- data

def import_backup(source):
    raw = json.loads(Path(source).read_text(encoding="utf-8"))
    records = []
    for venue in raw:
        record = {}
        for field in PUBLIC_FIELDS:
            value = venue.get(field)
            if value is None or value == "":
                continue
            if isinstance(value, str):
                value = DASHES.sub("-", value.strip())
            record[field] = value
        records.append(record)
    records.sort(key=lambda r: (r.get("sortOrder", 10**9), r.get("id", "")))
    return json.dumps(records, ensure_ascii=False, indent=2) + "\n"


def load_venues():
    venues = json.loads(DATA.read_text(encoding="utf-8"))
    errors, seen = [], set()
    for v in venues:
        vid = v.get("id", "?")
        for field in ("id", "name", "city", "address"):
            if not isinstance(v.get(field), str) or not v[field].strip():
                errors.append(f"{vid}: missing {field}")
        if vid in seen:
            errors.append(f"{vid}: duplicate id")
        seen.add(vid)
        extra = sorted(set(v) - set(PUBLIC_FIELDS))
        if extra:
            errors.append(f"{vid}: non-public fields {extra}; refresh with --import, never by copying the backup")
        if v.get("city") not in CITIES:
            errors.append(f"{vid}: unknown city {v.get('city')!r}; add it to CITIES in tools/build_directory.py")
        website = v.get("website")
        if website is not None and not re.match(r"https?://[^\s\"<>]+$", website):
            errors.append(f"{vid}: website must be an http(s) URL")
    if errors:
        sys.exit("data/venues.json is invalid:\n  " + "\n  ".join(errors))
    return venues


def group_by_city(venues):
    cities = {}
    for v in venues:
        cities.setdefault(v["city"], []).append(v)
    for halls in cities.values():
        halls.sort(key=lambda v: (v.get("sortOrder", 10**9), v["id"]))
    return cities


def area_of(address):
    """The part after the last comma, when it holds no digit: the district."""
    parts = [p.strip() for p in address.split(",")]
    if len(parts) < 2 or not parts[-1] or re.search(r"\d", parts[-1]):
        return None
    return parts[-1]


def areas_of(halls):
    found = []
    for v in halls:
        area = area_of(v["address"])
        if area and area not in found:
            found.append(area)
    return found


def phone_href(phone):
    digits = re.sub(r"[^\d+]", "", phone)
    return f"tel:{digits}" if len(re.sub(r"\D", "", digits)) >= 6 else None


# ---------------------------------------------------------------- pages

def url(path):
    return f"{BASE_URL}/{path}"


def jsonld(data):
    text = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    return text.replace("</", "<\\/")


def campaign_for(path):
    """A page's campaign from its site path: home, support, el-directory, el-athens, en-athens."""
    for root, lang in ((EL_ROOT, "el"), (EN_ROOT, "en")):
        if path.startswith(f"{root}/"):
            campaign = f"{lang}-{path[len(root) + 1:].strip('/') or 'directory'}"
            break
    else:
        campaign = {"en/": "en-home"}.get(path) or re.sub(r"\.html$", "", path) or "home"
    if len(campaign) > CAMPAIGN_MAX or not CAMPAIGN.fullmatch(campaign):
        sys.exit(f"{path!r} gives campaign {campaign!r}: use a-z, 0-9 and single hyphens, "
                 f"at most {CAMPAIGN_MAX} characters")
    return campaign


def play_url(campaign):
    """Play hands the referrer to the app on first open, so site installs show by page."""
    return (f"{PLAY_STORE}&referrer=utm_source%3Dwebsite%26utm_medium%3Dorganic"
            f"%26utm_campaign%3D{campaign}")


def app_store_url(campaign, token=None):
    """Plain until PROVIDER_TOKEN is set. Apple has no source field, so web- marks site installs."""
    token = PROVIDER_TOKEN if token is None else token
    if not token:
        return APP_STORE
    if not re.fullmatch(r"[A-Za-z0-9]+", token):
        sys.exit("PROVIDER_TOKEN must be letters and digits only")
    return f"https://apps.apple.com/app/apple-store/id{APP_STORE_ID}?pt={token}&ct=web-{campaign}&mt=8"


APPLE_GLYPH = ('<svg class="glyph" viewBox="0 0 24 24" aria-hidden="true"><path d="M16.4 12.6c0-2.4 2-3.6 '
               '2.1-3.7-1.1-1.7-2.9-1.9-3.5-1.9-1.5-.2-2.9.9-3.7.9-.8 0-1.9-.9-3.2-.8-1.6 0-3.1 1-4 2.4-1.7 3-.4 '
               '7.4 1.2 9.8.8 1.2 1.8 2.5 3 2.4 1.2 0 1.7-.8 3.1-.8 1.5 0 1.9.8 3.2.8 1.3 0 2.2-1.2 3-2.4.9-1.4 '
               '1.3-2.7 1.3-2.8-.1 0-2.5-1-2.5-3.9zM14 5.5c.7-.8 1.1-1.9 1-3-1 0-2.1.7-2.8 1.5-.6.7-1.2 1.8-1 '
               '2.9 1 .1 2.1-.6 2.8-1.4z"/></svg>')
PLAY_GLYPH = ('<svg class="glyph" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 2.8v18.4c0 .6.6 1 1.1.7l16-9.2'
              'c.5-.3.5-1.1 0-1.4l-16-9.2C4.6 1.8 4 2.2 4 2.8z"/></svg>')


def stores(lang, campaign):
    if lang == "el":
        apple, google, note = ("Λήψη από το", "Διαθέσιμο στο", "Για iPhone και Android.")
    else:
        apple, google, note = ("Download on the", "Get it on", "For iPhone and Android.")
    return (
        '<div class="stores">\n'
        f'  <a class="btn btn-primary btn-store" href="{esc(app_store_url(campaign))}">{APPLE_GLYPH}'
        f'<span><small>{apple}</small>App Store</span></a>\n'
        f'  <a class="btn btn-ghost btn-store" href="{esc(play_url(campaign))}">{PLAY_GLYPH}'
        f'<span><small>{google}</small>Google Play</span></a>\n'
        "</div>\n"
        f'<p class="stores-note">{note}</p>'
    )


def cta_card(lang, heading, text, campaign, root):
    """The download card: the page's pitch and store buttons beside the app's welcome screen."""
    shot = f"{root}assets/img/{lang}-welcome"
    alt = "Η οθόνη υποδοχής του RackUp" if lang == "el" else "The RackUp welcome screen"
    return f"""<section class="cta-card">
<div>
<h2>{heading}</h2>
<p>{text}</p>
{stores(lang, campaign)}
</div>
<div class="phone"><img src="{shot}-360.webp" srcset="{shot}-360.webp 360w, {shot}-720.webp 720w" sizes="180px" width="360" height="783" loading="lazy" alt="{alt}"></div>
</section>"""


def fit_description(head, areas, tail, label):
    """Adds district names to a meta description while it stays short. The label is plural, so never one."""
    chosen = []
    for area in areas:
        trial = f"{head} {label}: {', '.join(chosen + [area])}. {tail}"
        if len(trial) > DESCRIPTION_LIMIT:
            break
        chosen.append(area)
    if len(chosen) < 2:
        return f"{head} {tail}"
    return f"{head} {label}: {', '.join(chosen)}. {tail}"


# The site's shared header and footer, as on the hand-written pages. {root} reaches the site
# root, {home} and {dir} are the page language's home and directory, {alt} is this page in
# the other language.
WORDMARK = ('<a class="wordmark" href="{home}"><span class="ball b8" aria-hidden="true"><span class="n">8</span>'
            '</span><span class="wm">RACK<span>UP</span></span></a>')
HEADER = {
    "el": f"""<a class="skip-link" href="#main">Μετάβαση στο περιεχόμενο</a>
<header class="site-header">
  <div class="container nav">
    {WORDMARK}
    <nav class="nav-links" aria-label="Κύριο μενού">
      <a class="nav-text" href="{{dir}}">Αίθουσες</a>
      <a class="nav-text" href="{{home}}#how">Πώς δουλεύει</a>
      <a class="nav-text" href="{{root}}support.html">Βοήθεια</a>
      <a class="lang" href="{{alt}}" hreflang="en" lang="en">EN</a>
      <a class="btn btn-primary btn-sm" href="{{home}}#download">Κατέβασέ το</a>
    </nav>
  </div>
</header>""",
    "en": f"""<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header">
  <div class="container nav">
    {WORDMARK}
    <nav class="nav-links" aria-label="Main">
      <a class="nav-text" href="{{dir}}">Halls</a>
      <a class="nav-text" href="{{home}}#how">How it works</a>
      <a class="nav-text" href="{{root}}support.html">Help</a>
      <a class="lang" href="{{alt}}" hreflang="el" lang="el">ΕΛ</a>
      <a class="btn btn-primary btn-sm" href="{{home}}#download">Get the app</a>
    </nav>
  </div>
</header>""",
}
FOOTER = {
    "el": f"""<footer class="site-footer">
  <div class="container foot">
    <div>
      {WORDMARK}
      <p>Βρες αντίπαλο για μπιλιάρδο. Αμερικάνικο και γαλλικό, σε όλη την Ελλάδα.</p>
      <p>RackUp · Ιωάννινα</p>
    </div>
    <nav aria-label="Σύνδεσμοι">
      <a href="{{root}}{EL_ROOT}/">Αίθουσες μπιλιάρδου</a>
      <a href="{{root}}support.html">Υποστήριξη</a>
      <a href="{{root}}privacy.html">Απόρρητο</a>
      <a href="mailto:{EMAIL}">{EMAIL}</a>
    </nav>
  </div>
</footer>""",
    "en": f"""<footer class="site-footer">
  <div class="container foot">
    <div>
      {WORDMARK}
      <p>Find a billiards opponent. Pool and carom, across Greece.</p>
      <p>RackUp · Ioannina, Greece</p>
    </div>
    <nav aria-label="Links">
      <a href="{{root}}{EN_ROOT}/">Billiard halls</a>
      <a href="{{root}}support.html">Support</a>
      <a href="{{root}}privacy.html">Privacy Policy</a>
      <a href="mailto:{EMAIL}">{EMAIL}</a>
    </nav>
  </div>
</footer>""",
}
# The face the first paint needs: Greek pages are set in Commissioner, English ones in Space Grotesk.
PRELOAD_FONT = {"el": "commissioner-greek.woff2", "en": "space-grotesk-latin.woff2"}


def page(*, lang, title, description, path, alt_path, depth, body, data):
    prefix = "../" * depth
    el_path, en_path = (path, alt_path) if lang == "el" else (alt_path, path)
    locale = "el_GR" if lang == "el" else "en_GB"
    links = {"root": prefix, "home": prefix if lang == "el" else f"{prefix}en/",
             "dir": f"{prefix}{EL_ROOT if lang == 'el' else EN_ROOT}/", "alt": f"{prefix}{alt_path}"}
    return f"""<!DOCTYPE html>
{MARKER}
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{url(path)}">
<link rel="alternate" hreflang="el" href="{url(el_path)}">
<link rel="alternate" hreflang="en" href="{url(en_path)}">
<link rel="alternate" hreflang="x-default" href="{url(el_path)}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="RackUp">
<meta property="og:locale" content="{locale}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{url(path)}">
<meta property="og:image" content="{url('assets/og-card.png')}">
<meta name="theme-color" content="#0E1512">
<link rel="icon" type="image/png" href="{prefix}assets/icon-512.png">
<link rel="apple-touch-icon" href="{prefix}assets/icon-512.png">
<link rel="preload" as="font" type="font/woff2" crossorigin href="{prefix}assets/fonts/{PRELOAD_FONT[lang]}">
<link rel="stylesheet" href="{prefix}assets/site.css">
<script type="application/ld+json">{jsonld(data)}</script>
</head>
<body>
{HEADER[lang].format(**links)}
<main id="main">
{body}
</main>
{FOOTER[lang].format(**links)}
</body>
</html>
"""


def city_order(cities, lang):
    def key(city):
        name = CITIES[city][1] if lang == "el" else city
        return (-len(cities[city]), fold(name))
    return sorted(cities, key=key)


def index_page(cities, lang):
    total = sum(len(h) for h in cities.values())
    count = len(cities)
    root = EL_ROOT if lang == "el" else EN_ROOT
    campaign = campaign_for(f"{root}/")
    depth = root.count("/") + 1
    prefix = "../" * depth
    items, list_data = [], []
    for position, city in enumerate(city_order(cities, lang), start=1):
        slug, name_el, in_el = CITIES[city]
        name = name_el if lang == "el" else city
        n = len(cities[city])
        label = plural_el(n) if lang == "el" else plural_en(n)
        items.append(f'  <li><a href="{slug}/"><span class="city">{esc(name)}</span>'
                     f' <span class="count">{label}</span></a></li>')
        list_data.append({
            "@type": "ListItem",
            "position": position,
            "name": f"Μπιλιάρδο {in_el}" if lang == "el" else f"Billiards in {city}",
            "url": url(f"{root}/{slug}/"),
        })
    top_names = [CITIES[c][1] if lang == "el" else c for c in city_order(cities, lang)[:4]]
    if lang == "el":
        title = "Αίθουσες μπιλιάρδου στην Ελλάδα ανά πόλη | RackUp"
        description = (f"Κατάλογος με {total} αίθουσες μπιλιάρδου σε {count} πόλεις της Ελλάδας: "
                       f"{', '.join(top_names)} και άλλες. Δες τις διευθύνσεις και βρες αντίπαλο με το RackUp.")
        pitch = cta_card("el", "Βρες αντίπαλο στο RackUp",
                         "Ανέβασε αίθουσα, παιχνίδι (8άρα, 9άρα ή 10άρα) και ώρα, και δες ποιος θα πιάσει το "
                         "τραπέζι. Ή ζήτα να μπεις σε τραπέζι που άνοιξε κάποιος άλλος. Κάθε παίκτης έχει "
                         "κατηγορία, από Pro μέχρι E, για να ξέρεις τι σε περιμένει.", campaign, prefix)
        body = f"""<section class="page-hero">
<div class="container">
<p class="crumbs"><a href="{prefix}">RackUp</a> › Αίθουσες μπιλιάρδου</p>
<h1>Αίθουσες μπιλιάρδου στην Ελλάδα</h1>
<p class="lead">Ψάχνεις πού να παίξεις μπιλιάρδο; Εδώ θα βρεις {total} αίθουσες σε {count} πόλεις, με τη διεύθυνση της καθεμιάς. Τον κατάλογο τον φτιάξαμε στο χέρι για το RackUp, την εφαρμογή που σε φέρνει σε επαφή με άλλους παίκτες για παιχνίδι στην τσόχα.</p>
</div>
</section>
<div class="container">
<h2>Διάλεξε πόλη</h2>
<ul class="city-grid">
{chr(10).join(items)}
</ul>
{pitch}
<p class="note">Λείπει η αίθουσά σου ή βρήκες κάποιο λάθος; Γράψε μας στο <a href="mailto:{EMAIL}">{EMAIL}</a>.</p>
</div>"""
        list_name = "Αίθουσες μπιλιάρδου στην Ελλάδα ανά πόλη"
    else:
        title = "Billiard halls in Greece by city | RackUp"
        description = (f"A directory of {total} billiard halls in {count} Greek cities: "
                       f"{', '.join(top_names)} and more. See the addresses and find an opponent with RackUp.")
        pitch = cta_card("en", "Find an opponent on RackUp",
                         "Post the hall, the game (8-Ball, 9-Ball or 10-Ball) and the time, and see who takes the "
                         "table. Or ask to join a table someone else has posted. Every player carries a category "
                         "from Pro down to E, so you know what you are walking into.", campaign, prefix)
        body = f"""<section class="page-hero">
<div class="container">
<p class="crumbs"><a href="{prefix}">RackUp</a> › Billiard halls</p>
<h1>Billiard halls in Greece</h1>
<p class="lead">Looking for somewhere to play billiards? Here are {total} halls in {count} cities, each with its address. We researched the directory by hand for RackUp, the app that puts you in touch with other players for a game on a real table.</p>
</div>
</section>
<div class="container">
<h2>Pick a city</h2>
<ul class="city-grid">
{chr(10).join(items)}
</ul>
{pitch}
<p class="note">Is your hall missing, or did you spot a mistake? Email us at <a href="mailto:{EMAIL}">{EMAIL}</a>.</p>
</div>"""
        list_name = "Billiard halls in Greece by city"
    alt_root = EN_ROOT if lang == "el" else EL_ROOT
    data = {"@context": "https://schema.org", "@type": "ItemList", "name": list_name,
            "numberOfItems": count, "itemListElement": list_data}
    return page(lang=lang, title=title, description=description, path=f"{root}/",
                alt_path=f"{alt_root}/", depth=depth, body=body, data=data)


def hall_item(v, lang):
    parts = [f'<li class="hall" id="{esc(v["id"])}">',
             f'  <h2>{esc(v["name"])}</h2>',
             f'  <p class="addr">{esc(v["address"])}</p>']
    phone = v.get("phone")
    if phone:
        label = "Τηλέφωνο" if lang == "el" else "Phone"
        href = phone_href(phone)
        shown = f'<a href="{esc(href)}">{esc(phone)}</a>' if href else esc(phone)
        parts.append(f'  <p class="contact">{label}: {shown}</p>')
    website = v.get("website")
    if website:
        label = "Ιστοσελίδα" if lang == "el" else "Website"
        host = re.sub(r"^https?://(www\.)?", "", website).rstrip("/")
        parts.append(f'  <p class="contact">{label}: <a href="{esc(website)}" rel="noopener">{esc(host)}</a></p>')
    parts.append("</li>")
    return "\n".join(parts)


def business(v):
    """LocalBusiness from the fields the directory holds, and nothing more."""
    item = {
        "@type": "LocalBusiness",
        "name": v["name"],
        "address": {
            "@type": "PostalAddress",
            "streetAddress": v["address"],
            "addressLocality": CITIES[v["city"]][1],
            "addressCountry": "GR",
        },
    }
    if v.get("phone"):
        item["telephone"] = v["phone"]
    if v.get("website"):
        item["url"] = v["website"]
    return item


def city_page(city, halls, cities, lang):
    slug, name_el, in_el = CITIES[city]
    n = len(halls)
    # One district among several halls reads as if every hall were there.
    areas = areas_of(halls)
    if len(areas) < 2:
        areas = []
    root = EL_ROOT if lang == "el" else EN_ROOT
    alt_root = EN_ROOT if lang == "el" else EL_ROOT
    path = f"{root}/{slug}/"
    campaign = campaign_for(path)
    depth = root.count("/") + 2
    prefix = "../" * depth
    hall_list = "\n".join(hall_item(v, lang) for v in halls)
    others = sorted((c for c in cities if c != city),
                    key=lambda c: fold(CITIES[c][1] if lang == "el" else c))
    if lang == "el":
        heading = f"Μπιλιάρδο {in_el}"
        if n == 1:
            title = f"{heading}: {halls[0]['name']} | RackUp"
            description = f"{heading}: {halls[0]['name']}, {halls[0]['address']}. Βρες αντίπαλο με το RackUp."
        else:
            title = f"{heading}: {plural_el(n)} | RackUp"
            description = fit_description(f"{heading}: δες {n} αίθουσες και τις διευθύνσεις τους.",
                                          areas, "Βρες αντίπαλο με το RackUp.", "Περιοχές")
        lead = f"{plural_el(n)} μπιλιάρδου {in_el}."
        if areas and n > 1:
            lead += f" Περιοχές: {esc(', '.join(areas))}."
        other_links = " ".join(f'<li><a class="chip" href="../{CITIES[c][0]}/">{esc(CITIES[c][1])}</a></li>'
                               for c in others)
        pitch = cta_card("el", f"Θες αντίπαλο {esc(in_el)};",
                         "Ανέβασε στο RackUp αίθουσα, παιχνίδι (8άρα, 9άρα ή 10άρα) και ώρα, και δες ποιος θα "
                         "πιάσει το τραπέζι. Ή ζήτα να μπεις σε τραπέζι που άνοιξε κάποιος άλλος.", campaign, prefix)
        body = f"""<section class="page-hero">
<div class="container">
<p class="crumbs"><a href="../../">RackUp</a> › <a href="../">Αίθουσες μπιλιάρδου</a> › {esc(name_el)}</p>
<h1>{esc(heading)}</h1>
<p class="lead">{lead}</p>
</div>
</section>
<div class="container">
<ul class="halls">
{hall_list}
</ul>
{pitch}
<p class="note">Ο κατάλογος είναι φτιαγμένος στο χέρι και κάτι μπορεί να έχει αλλάξει. Λείπει η αίθουσά σου ή βρήκες κάποιο λάθος; Γράψε μας στο <a href="mailto:{EMAIL}">{EMAIL}</a>.</p>
<nav class="other" aria-label="Άλλες πόλεις">
<h2>Άλλες πόλεις</h2>
<ul class="chips">{other_links}</ul>
</nav>
</div>"""
        crumbs = [("RackUp", url("")), ("Αίθουσες μπιλιάρδου", url(f"{root}/")), (name_el, url(path))]
    else:
        heading = f"Billiards in {city}"
        if n == 1:
            title = f"{heading}: {halls[0]['name']} | RackUp"
            description = f"{heading}: {halls[0]['name']}, {halls[0]['address']}. Find an opponent with RackUp."
        else:
            title = f"{heading}: {plural_en(n)} | RackUp"
            description = (f"{heading}: see {n} billiard halls and their addresses, "
                           f"from a hand-researched directory. Find an opponent with RackUp.")
        lead = f"{plural_en(n).replace('hall', 'billiard hall')} in {esc(city)} ({esc(name_el)})."
        other_links = " ".join(f'<li><a class="chip" href="../{CITIES[c][0]}/">{esc(c)}</a></li>' for c in others)
        pitch = cta_card("en", f"Looking for an opponent in {esc(city)}?",
                         "Post the hall, the game (8-Ball, 9-Ball or 10-Ball) and the time on RackUp, and see who "
                         "takes the table. Or ask to join a table someone else has posted.", campaign, prefix)
        body = f"""<section class="page-hero">
<div class="container">
<p class="crumbs"><a href="../../../">RackUp</a> › <a href="../">Billiard halls</a> › {esc(city)}</p>
<h1>{esc(heading)}</h1>
<p class="lead">{lead}</p>
</div>
</section>
<div class="container">
<ul class="halls">
{hall_list}
</ul>
{pitch}
<p class="note">The directory is researched by hand, so something may have changed. Is your hall missing, or did you spot a mistake? Email us at <a href="mailto:{EMAIL}">{EMAIL}</a>.</p>
<nav class="other" aria-label="Other cities">
<h2>Other cities</h2>
<ul class="chips">{other_links}</ul>
</nav>
</div>"""
        crumbs = [("RackUp", url("")), ("Billiard halls", url(f"{root}/")), (city, url(path))]
    data = {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "BreadcrumbList", "itemListElement": [
                {"@type": "ListItem", "position": i, "name": name, "item": link}
                for i, (name, link) in enumerate(crumbs, start=1)]},
            {"@type": "ItemList", "name": heading, "numberOfItems": n, "itemListElement": [
                {"@type": "ListItem", "position": i, "item": business(v)}
                for i, v in enumerate(halls, start=1)]},
        ],
    }
    return page(lang=lang, title=title, description=description, path=path,
                alt_path=f"{alt_root}/{slug}/", depth=depth, body=body, data=data)


def sitemap(cities):
    paths = ["", "en/", "support.html", "privacy.html", f"{EL_ROOT}/", f"{EN_ROOT}/"]
    for city in city_order(cities, "el"):
        slug = CITIES[city][0]
        paths += [f"{EL_ROOT}/{slug}/", f"{EN_ROOT}/{slug}/"]
    entries = "\n".join(f"  <url><loc>{url(p)}</loc></url>" for p in paths)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{entries}\n</urlset>\n")


def home_with_counts(text, cities):
    """The homes are hand-written; only their data-count spans, city grid and store links are ours."""
    counts = {"venues": sum(len(h) for h in cities.values()), "cities": len(cities)}
    for key, value in counts.items():
        text, found = re.subn(rf'(<span data-count="{key}">)\d+(</span>)', rf"\g<1>{value}\g<2>", text)
        if not found:
            sys.exit(f'a home page has no <span data-count="{key}"> to update')
    return text


def city_grid(cities, lang):
    """Every city and its hall count, linked relative to the home of that language."""
    root = EL_ROOT if lang == "el" else EN_ROOT[len("en/"):]
    items = []
    for city in city_order(cities, lang):
        slug, name_el, _ = CITIES[city]
        n = len(cities[city])
        label = plural_el(n) if lang == "el" else plural_en(n)
        name = name_el if lang == "el" else city
        items.append(f'  <li><a href="{root}/{slug}/"><span class="city">{esc(name)}</span>'
                     f' <span class="count">{label}</span></a></li>')
    return '<ul class="city-grid">\n' + "\n".join(items) + "\n</ul>"


def home_with_city_grid(text, cities, lang):
    start, end = text.find(GRID_START), text.find(GRID_END)
    if start < 0 or end < start:
        sys.exit(f"a home page has no {GRID_START} ... {GRID_END} block for the city grid")
    return text[:start + len(GRID_START)] + "\n" + city_grid(cities, lang) + "\n" + text[end:]


def with_store_links(name, text):
    """Tags every store href on a hand-written page with that page's campaign."""
    campaign = campaign_for(HAND_PAGES[name])
    play = f'href="{esc(play_url(campaign))}"'
    apple = f'href="{esc(app_store_url(campaign))}"'
    text, plays = re.subn(r'href="https://play\.google\.com/[^"]*"', lambda _: play, text)
    text, apples = re.subn(r'href="https://apps\.apple\.com/[^"]*"', lambda _: apple, text)
    if not plays or not apples:
        sys.exit(f"{name} has no store links to tag; drop it from HAND_PAGES if that is intended")
    return text


def render():
    cities = group_by_city(load_venues())
    files = {ROOT / "sitemap.xml": sitemap(cities)}
    for name in HAND_PAGES:
        text = (ROOT / name).read_text(encoding="utf-8")
        if name in HOMES:
            text = home_with_city_grid(home_with_counts(text, cities), cities, HOMES[name])
        files[ROOT / name] = with_store_links(name, text)
    for lang, root in (("el", EL_ROOT), ("en", EN_ROOT)):
        files[ROOT / root / "index.html"] = index_page(cities, lang)
        for city, halls in cities.items():
            files[ROOT / root / CITIES[city][0] / "index.html"] = city_page(city, halls, cities, lang)
    for path, text in files.items():
        if DASHES.search(text):
            sys.exit(f"{path.relative_to(ROOT)} would contain an en or em dash; fix the copy or the data")
    return files


def stale_generated_dirs(files):
    """City folders this script made earlier for a city that has since gone."""
    stale = []
    for root in (EL_ROOT, EN_ROOT):
        base = ROOT / root
        if not base.is_dir():
            continue
        for child in base.iterdir():
            page_file = child / "index.html"
            if (child.is_dir() and page_file not in files and page_file.is_file()
                    and MARKER in page_file.read_text(encoding="utf-8")):
                stale.append(child)
    return stale


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--import", dest="source", metavar="PATH",
                        help="refresh data/venues.json from the app repo's data/venues-backup.json")
    parser.add_argument("--check", action="store_true", help="exit 1 if any page is out of date")
    args = parser.parse_args()

    if args.source:
        DATA.parent.mkdir(parents=True, exist_ok=True)
        DATA.write_text(import_backup(args.source), encoding="utf-8", newline="\n")
        print(f"Imported {args.source} into {DATA.relative_to(ROOT)}")

    files = render()
    stale = stale_generated_dirs(files)
    if args.check:
        outdated = [p for p, t in files.items() if not p.is_file() or p.read_text(encoding="utf-8") != t]
        for p in outdated + stale:
            print(f"out of date: {p.relative_to(ROOT)}")
        sys.exit(1 if outdated or stale else 0)

    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    for folder in stale:
        shutil.rmtree(folder)
        print(f"removed {folder.relative_to(ROOT)}")
    cities = group_by_city(load_venues())
    print(f"Wrote {len(files) - 1 - len(HAND_PAGES)} directory pages for {sum(map(len, cities.values()))} halls "
          f"in {len(cities)} cities, plus sitemap.xml, the counts in index.html and the store links "
          f"in {' and '.join(HAND_PAGES)}")


if __name__ == "__main__":
    main()
